import Link from 'next/link'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter();

  const handleClick = () => {
    console.log('Placing your Order');
    router.push('/product');
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1> Home Page </h1>

        <Link href='/blog'>
          Blog
        </Link>
        <Link href='/product'>
          Products
        </Link>
      </div>
      <div>
        <button onClick={handleClick}>
          Place Order
        </button>
      </div>
    </>
  )
}
